org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = com.sakuraryoko
mod_id = ap_scan
mod_name = Audio Player Scanner
author = Sakura-Ryoko
mod_file_name = ap_scan

# Current mod version
mod_version = 1.0.7

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.2
minecraft_version = 26.2

fabric_loader_version = 0.19.3
fabric_api_version = 0.158.0+26.2
conditionalmixin_version = 0.6.4

# For Any API Hooks, etc
voice_chat_mc_version=26.2
voice_chat_version=2.6.22
audio_player_mc_version=26.2
audio_player_version=2.4.0
audio_player_roleplay_mc_version=26.2
audio_player_roleplay_version=0.3.0
