org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = com.sakuraryoko
mod_id = ap_scan
mod_name = Audio Player Scanner
author = Sakura-Ryoko
mod_file_name = ap_scan

# Current mod version
mod_version = 1.0.6

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.1.2
minecraft_version = 26.1.2

fabric_loader_version = 0.19.2
fabric_api_version = 0.149.1+26.1.2
